on: [pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: License compliance check
        uses: mikaelvesavuori/license-compliance-action@v1.0.2
        with:
          allow_licenses: "MIT;Apache-2.0"